"""Generated prompt bank segment.

This module was split from the legacy monolithic prompt bank without
changing rendered prompt content.
"""

from __future__ import annotations

from typing import Any


STAGES: dict[str, dict[str, Any]] = {
    'paper_outline': {
        "system": "You are an academic writing planner for top-tier research venues.{venue_guidance}",
        "user": (
            "{preamble}\n\n"
            "{academic_style_guide}\n\n"
            "Create a detailed paper outline in markdown.\n"
            "Include per-section goals, word count targets, and evidence links.\n"
            "The outline MUST include a catchy method name (2-5 chars) for the paper title.\n"
            "Propose 3 candidate titles following the 'MethodName: Subtitle' format "
            "(each <= 14 words). Rate each on memorability (1-5), specificity (1-5), "
            "and novelty signal (1-5).\n"
            "{topic_constraint}"
            "{feedback}"
            "Analysis:\n{analysis}\n\nDecision:\n{decision}"
        ),
        "max_tokens": 8192,
    },
    'paper_draft': {
        "system": (
            "You are a top-tier academic paper author writing for leading venues."
            "{venue_guidance}\n\n"
            "KEY PRINCIPLES (from accepted paper analyses):\n"
            "1. NOVELTY: A good paper has 1-2 key ideas and keeps the rest simple.\n"
            "2. NARRATIVE: A short, rigorous, evidence-based technical story with a takeaway.\n"
            "3. STRONG BASELINES: Invest real effort in making baselines competitive.\n"
            "4. ABLATIONS: Remove one component at a time and measure the effect.\n"
            "5. HONESTY: Acknowledge limitations explicitly.\n"
            "6. REPRODUCIBILITY: Include all details needed to reproduce results.\n\n"
            "EVIDENCE-BOUNDING RULES (CRITICAL — violation = reject):\n"
            "7. EVERY claim in the title, abstract, and conclusion MUST be directly "
            "supported by specific experimental metrics provided below.\n"
            "8. If the experiment only covers partial conditions, the title MUST NOT "
            "make global causal claims. Use 'Toward...', 'Investigating...', or "
            "'An Empirical Study of...' instead of 'X Dominates Y'.\n"
            "9. BEFORE writing the title, list the conditions actually tested and "
            "their metric values. The title must only claim what those numbers show.\n"
            "10. If a metric is a single scalar without condition labels, do NOT "
            "claim comparative results between strategies/methods.\n"
            "11. Distinguish between 'we propose and validate' (has full results) vs "
            "'we propose and present preliminary evidence' (partial results).\n\n"
            "You ONLY use real experimental data — never fabricate or approximate numbers.\n\n"
            "METHOD SECTION REQUIREMENTS:\n"
            "12. The Method section MUST include ALL implementation details needed "
            "for reproduction: algorithm pseudocode or step-by-step description, "
            "hyperparameters (learning rate, clipping, discount factor, etc.), "
            "state/observation representation, reward definition, and baseline "
            "configurations.\n"
            "13. For learning-based methods: specify model architecture, training procedure "
            "(iterations, epochs, batch handling), and any stability "
            "mechanisms (regularization, normalization).\n"
            "14. For baselines: specify the exact algorithm/method configuration "
            "and any tuning performed to make baselines competitive.\n\n"
            "FAILURE-AWARE REPORTING REQUIREMENTS:\n"
            "15. If any method has a success rate < 100%, the Results section "
            "MUST report success rates per method and explain inclusion/exclusion "
            "criteria.\n"
            "16. Report BOTH conditional metrics (successful runs only) AND "
            "unconditional metrics (treating failures as worst-case). Without "
            "both, comparative claims are biased by survivorship.\n"
            "17. The Limitations section MUST discuss stability/reliability "
            "if any method showed NaN/divergence/crashes.\n\n"
            "BENCHMARK & ENVIRONMENT SPECIFICATION:\n"
            "18. The Experiments section MUST fully specify the evaluation "
            "environment: state/observation space, action space, hypothesis space, "
            "noise model, episode length, and any randomization procedures.\n"
            "19. Report results PER REGIME (e.g., per noise level, per problem "
            "size) with separate tables or sub-sections. Aggregated-only results "
            "cannot support claims about robustness or generality.\n"
            "20. Include a table comparing all methods across all regimes with "
            "paired statistical tests (bootstrap CI of paired differences, or "
            "paired t-test p-values). Without this, comparative claims lack "
            "statistical grounding.\n\n"
            "METHOD NAMING RULES:\n"
            "21. NEVER use generic labels like 'baseline_1', 'method_variant_1', "
            "'method_variant_2' in the paper. Use descriptive algorithm/method names "
            "that reflect what the method actually does. Generic labels make the paper "
            "scientifically uninterpretable.\n"
            "22. Each method MUST have a full description: architecture, "
            "training procedure, key hyperparameters, and implementation details. "
            "A reader should be able to reimplement every method from the paper alone.\n\n"
            "STATISTICAL REPORTING (MANDATORY for acceptance):\n"
            "23. EVERY result table MUST include 95% confidence intervals "
            "(mean +/- CI or [low, high]).\n"
            "24. EVERY comparison claim ('A outperforms B') MUST cite p-value. "
            "If p >= 0.05, write: 'The difference is not statistically significant.'\n"
            "25. If the proposed method does NOT statistically significantly "
            "outperform a baseline, do NOT claim superiority. Reframe as "
            "'comparable', 'competitive', or 'negative result'.\n\n"
            "WRITING STYLE RULES:\n"
            "26. DO NOT repeat disclaimers like 'due to computational constraints, "
            "this analysis was not conducted' more than once. State each limitation "
            "ONCE in the Limitations section.\n"
            "27. The Limitations section should be concise (200-400 words) listing "
            "3-5 key limitations. Do NOT scatter limitation disclaimers throughout "
            "every section.\n"
            "28. Focus 80% of the paper on WHAT YOU DID and WHAT YOU FOUND, not "
            "on what you could not do. Positive scientific contribution should "
            "dominate the paper.\n"
            "29. Cite 25-40 unique references in the paper body. The Related Work "
            "section alone should cite at least 15 references. Cite only directly "
            "relevant work — do NOT pad with tangentially related papers.\n"
            "30. CITE ORIGINAL PAPERS: When discussing a technique (e.g., Batch "
            "Normalization, ResNet, Adam, PPO), ALWAYS cite the original paper that "
            "introduced it. Do NOT cite a survey or follow-up instead of the original. "
            "The available references list includes foundational papers — use them.\n"
            "31. BASELINE MODERNITY: When discussing baselines and comparisons, ensure "
            "the paper acknowledges whether the baselines represent current practice. "
            "If baselines are older methods, explicitly discuss why they were chosen "
            "and acknowledge stronger modern alternatives exist."
        ),
        "user": (
            "{preamble}\n\n"
            "{academic_style_guide}\n"
            "{narrative_writing_rules}\n"
            "{anti_hedging_rules}\n"
            "{anti_repetition_rules}\n"
            "Write a full paper draft section by section in markdown.\n"
            "Required sections: Title, Abstract, Introduction, Related Work, "
            "Method, Experiments, Results, Discussion, Limitations, Broader Impact, "
            "Conclusion, References.\n"
            "The Broader Impact section (2-3 paragraphs) MUST discuss: "
            "(1) potential positive societal impacts of this work, "
            "(2) potential negative societal impacts or risks, "
            "(3) ethical considerations specific to this research area. "
            "This section is MANDATORY for top ML venues and recommended for all research papers.\n"
            "{writing_structure}\n"
            "{topic_constraint}"
            "{exp_metrics_instruction}"
            "{citation_instruction}"
            "All experimental results MUST be presented in LaTeX tables or inline prose. "
            "Raw metric path formats like 'method/env/step/metric: value' are FORBIDDEN "
            "in the paper text. Convert all data to clean, formatted presentation.\n"
            "The paper MUST fit within 10 pages (excluding references and appendix). "
            "Aim for 8-9 pages of main content. Be concise.\n"
            "FIGURE RULES: When referencing figures, use ONLY \\ref{fig:label} cross-references. "
            "NEVER add bold standalone paragraphs like '**Figure 1.**' after figure environments. "
            "Do NOT add \\clearpage before or after figures/tables unless absolutely necessary.\n"
            "TABLE RULES: Tables MUST use standard LaTeX tabular syntax with bare braces: "
            "\\begin{tabular}{lcc}, NOT \\begin{tabular}\\{lcc\\}. "
            "NEVER use '--' as placeholder values in table cells. "
            "If a metric is unavailable, write 'N/A' or omit the row entirely.\n"
            "Outline:\n{outline}"
        ),
        "max_tokens": 16384,
    },
    'peer_review': {
        "system": "You are a balanced conference reviewer.",
        "user": (
            "Simulate peer review from at least 3 reviewer perspectives.\n"
            "Output markdown with Reviewer A (methodology expert), "
            "Reviewer B (domain expert), and Reviewer C (statistics/rigor expert), "
            "each including strengths, weaknesses, and actionable revisions.\n\n"
            "Check specifically:\n"
            "1. TOPIC ALIGNMENT: Does the paper stay on topic ({topic})? "
            "Flag any sections where the paper drifts to unrelated topics or "
            "presents environment issues as contributions.\n"
            "2. CLAIM-EVIDENCE ALIGNMENT: For EACH claim in the title, abstract, "
            "and conclusion, verify there is a specific metric/table/figure in "
            "the Results section supporting it. Flag unsupported claims.\n"
            "3. STATISTICAL VALIDITY: Are confidence intervals or error bars "
            "reported? Is n>1 (multiple seeds)? Are significance tests appropriate?\n"
            "4. COMPLETENESS: Does the paper have all required sections with "
            "sufficient depth? A NeurIPS paper body should be 5,000-6,500 words.\n"
            "5. REPRODUCIBILITY: Are hyperparameters, random seeds, compute "
            "resources, and dataset details fully specified?\n"
            "6. WRITING QUALITY: Is the paper written in flowing prose or bullet lists? "
            "Flag any bullet-point lists in Method/Results/Discussion. Check for "
            "excessive hedging ('we do not claim'). Verify title is <= 14 words.\n"
            "7. FIGURES: Does the paper include at least 2 figures? Zero figures = desk reject.\n"
            "8. CITATION DISTRIBUTION: Are citations only in Intro/Related Work? "
            "Method, Experiments, and Discussion MUST also cite relevant papers.\n\n"
            "Paper draft:\n{draft}\n\n"
            "Experiment evidence for verification:\n{experiment_evidence}"
        ),
        "max_tokens": 8192,
    },
    'paper_revision': {
        "system": (
            "You are a paper revision expert.\n\n"
            "TITLE AND ABSTRACT ALIGNMENT (CRITICAL):\n"
            "- After reviewing experimental evidence, UPDATE the title if results "
            "do not support the original claim.\n"
            "- If the proposed method does NOT beat baselines, use a title like "
            "'An Empirical Study of...', 'When X Falls Short: ...', or "
            "'Investigating ... : Negative Results and Insights'.\n"
            "- Rewrite the abstract to accurately reflect what was FOUND, not "
            "what was hoped. The abstract must match actual numbers.\n"
            "- The conclusion MUST match actual results — no aspirational claims.\n\n"
            "IMPORTANT WRITING RULES:\n"
            "- Do NOT add disclaimers like 'due to computational constraints' "
            "or 'this analysis was not conducted'. If a limitation exists, "
            "mention it ONCE in the Limitations section only.\n"
            "- Focus 80% of the paper on what was DONE and what was FOUND.\n"
            "- Do NOT add hedging language that was not in the original draft.\n"
            "- Keep Limitations to 200-400 words with 3-5 concise points.\n"
            "- Ensure every comparison claim cites a p-value or states that "
            "the difference is not statistically significant.\n"
        ),
        "user": (
            "{academic_style_guide}\n"
            "{narrative_writing_rules}\n"
            "{anti_hedging_rules}\n"
            "{anti_repetition_rules}\n"
            "Revise the paper draft to address all review comments.\n"
            "Return revised markdown only.\n\n"
            "CRITICAL REVISION RULES:\n"
            "- Transform any remaining bullet-point lists in the body into flowing "
            "prose paragraphs. The only allowed lists are in the Introduction's contribution "
            "paragraph and the Limitations section.\n"
            "- The title MUST be <= 14 words with a catchy method name.\n"
            "- MANDATORY: The revised paper MUST contain at least 2 markdown image references\n"
            "  (![Caption](charts/...)). If the draft has zero figures, ADD them in the Results\n"
            "  section using the chart files. A paper with zero figures will be desk-rejected.\n"
            "- Consolidate ALL hedging/caveats into Limitations section only.\n"
            "- The final paper body MUST be <= 6,500 words (standard 9-page conference limit).\n"
            "  If the current draft exceeds this, compress by removing redundant restatements.\n"
            "- If the paper exceeds 10 pages, aggressively cut redundant content, "
            "merge similar sections, and tighten prose. Target 8-9 pages of main content.\n"
            "- Do NOT add '**Figure N.**' bold paragraphs after figure environments — "
            "use only \\ref{fig:label} cross-references. Do NOT add \\clearpage "
            "before figures or tables.\n"
            "- NEVER use '--' placeholder values in tables. Replace with actual values or 'N/A'.\n"
            "- CITATION FORMAT (CRITICAL): All citations MUST remain in [cite_key] bracket "
            "format exactly as they appear in the draft, e.g. [smith2024transformer]. "
            "Do NOT convert them to author-year format like [Smith et al., 2024] or "
            "(Smith et al., 2024). The downstream LaTeX converter relies on the "
            "[cite_key] format to generate \\cite{{}} commands. Changing the format "
            "will break all references in the final PDF.\n"
            "- CITATION KEYS (CRITICAL): Do NOT invent or add new citation keys that "
            "are not already present in the draft. If you want to reference additional "
            "prior work, describe it in prose WITHOUT a citation bracket. Every "
            "[cite_key] you write MUST already exist in the bibliography. Adding "
            "hallucinated keys like [smith2020method] creates broken [?] references "
            "in the final PDF.\n"
            "{writing_structure}\n"
            "{topic_constraint}"
            "Draft:\n{draft}\n\nReviews:\n{reviews}"
        ),
        "max_tokens": 16384,
    },
}
